[project]
name = "periodicos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.2",
    "mysql-connector-python>=9.5.0",
    "mysqlclient>=2.2.7",
]
